package com.coreyja.tornadosafezone;

import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.MarkerOptions;

/**
 * Created by coreyja on 12/8/13.
 */
public class SafeZone {

    private LatLng position;
    private String title;
    private String address, city, state;
    private String phone;

    /* The hours of the SafeZone. The hours are in 24 hour format. The minutes are just minutes. */
    private int openMinute, openHour;
    private int closeMinute, closeHour;

    private int capacity;

    private String extra_info;


    public SafeZone(LatLng position, String title, String address, String city, String state, String phone, int openHour, int openMinute, int closeHour, int closeMinute, int capacity, String extra_info) {
        this.position = position;
        this.title = title;
        this.address = address;
        this.city = city;
        this.state = state;
        this.phone = phone;
        this.openMinute = openMinute;
        this.openHour = openHour;
        this.closeMinute = closeMinute;
        this.closeHour = closeHour;
        this.capacity = capacity;
        this.extra_info = extra_info;
    }

    public SafeZone(LatLng position, String title, String address, String city, String state, String phone, int openHour, int openMinute, int closeHour, int closeMinute, int capacity) {
        this(position, title, address, city, state, phone, openHour, openMinute, closeHour, closeMinute, capacity, "");
    }

    public SafeZone(LatLng position, String title, String address, String city, String state, String phone, int openHour, int openMinute, int closeHour, int closeMinute) {
        this(position, title, address, city, state, phone, openHour, openMinute, closeHour, closeMinute, 0, "");
    }

    public SafeZone(LatLng position, String title, String address, String city, String state, String phone) {
        this(position, title, address, city, state, phone, -1, 0, -1, 0, 0, "");
    }

    public SafeZone(LatLng position, String title, String address, String city, String state) {
        this(position, title, address, city, state, "", -1, 0, -1, 0, 0, "");
    }

    public SafeZone(LatLng position, String title) {
        this(position, title, "", "", "", "", -1, 0, -1, 0, 0, "");
    }


    /* Getters and Setters autogenerated by Android Studio */
    public LatLng getPosition() {
        return position;
    }

    public void setPosition(LatLng position) {
        this.position = position;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public int getOpenMinute() {
        return openMinute;
    }

    public void setOpenMinute(int openMinute) {
        this.openMinute = openMinute;
    }

    public int getOpenHour() {
        return openHour;
    }

    public void setOpenHour(int openHour) {
        this.openHour = openHour;
    }

    public int getCloseMinute() {
        return closeMinute;
    }

    public void setCloseMinute(int closeMinute) {
        this.closeMinute = closeMinute;
    }

    public int getCloseHour() {
        return closeHour;
    }

    public void setCloseHour(int closeHour) {
        this.closeHour = closeHour;
    }

    public int getCapacity() {
        return capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public String getExtra_info() {
        return extra_info;
    }

    public void setExtra_info(String extra_info) {
        this.extra_info = extra_info;
    }

    // Create and return a new MarkerOptions object using the position of this SafeZone
    public MarkerOptions generateMarkerOptions() {
        return new MarkerOptions().position(this.position);
    }


}
