/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-13 at 08:31:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.perfect_atrium_421.safezones.model;

/**
 * Model definition for Hours.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the safezones. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Hours extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String friClose;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String friOpen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String monClose;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String monOpen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String satClose;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String satOpen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String sunClose;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String sunOpen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String thursClose;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String thursOpen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String tueClose;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String tueOpen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String wedClose;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String wedOpen;

  /**
   * @return value or {@code null} for none
   */
  public String getFriClose() {
    return friClose;
  }

  /**
   * @param friClose friClose or {@code null} for none
   */
  public Hours setFriClose(String friClose) {
    this.friClose = friClose;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getFriOpen() {
    return friOpen;
  }

  /**
   * @param friOpen friOpen or {@code null} for none
   */
  public Hours setFriOpen(String friOpen) {
    this.friOpen = friOpen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Hours setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getMonClose() {
    return monClose;
  }

  /**
   * @param monClose monClose or {@code null} for none
   */
  public Hours setMonClose(String monClose) {
    this.monClose = monClose;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getMonOpen() {
    return monOpen;
  }

  /**
   * @param monOpen monOpen or {@code null} for none
   */
  public Hours setMonOpen(String monOpen) {
    this.monOpen = monOpen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSatClose() {
    return satClose;
  }

  /**
   * @param satClose satClose or {@code null} for none
   */
  public Hours setSatClose(String satClose) {
    this.satClose = satClose;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSatOpen() {
    return satOpen;
  }

  /**
   * @param satOpen satOpen or {@code null} for none
   */
  public Hours setSatOpen(String satOpen) {
    this.satOpen = satOpen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSunClose() {
    return sunClose;
  }

  /**
   * @param sunClose sunClose or {@code null} for none
   */
  public Hours setSunClose(String sunClose) {
    this.sunClose = sunClose;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSunOpen() {
    return sunOpen;
  }

  /**
   * @param sunOpen sunOpen or {@code null} for none
   */
  public Hours setSunOpen(String sunOpen) {
    this.sunOpen = sunOpen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getThursClose() {
    return thursClose;
  }

  /**
   * @param thursClose thursClose or {@code null} for none
   */
  public Hours setThursClose(String thursClose) {
    this.thursClose = thursClose;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getThursOpen() {
    return thursOpen;
  }

  /**
   * @param thursOpen thursOpen or {@code null} for none
   */
  public Hours setThursOpen(String thursOpen) {
    this.thursOpen = thursOpen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getTueClose() {
    return tueClose;
  }

  /**
   * @param tueClose tueClose or {@code null} for none
   */
  public Hours setTueClose(String tueClose) {
    this.tueClose = tueClose;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getTueOpen() {
    return tueOpen;
  }

  /**
   * @param tueOpen tueOpen or {@code null} for none
   */
  public Hours setTueOpen(String tueOpen) {
    this.tueOpen = tueOpen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getWedClose() {
    return wedClose;
  }

  /**
   * @param wedClose wedClose or {@code null} for none
   */
  public Hours setWedClose(String wedClose) {
    this.wedClose = wedClose;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getWedOpen() {
    return wedOpen;
  }

  /**
   * @param wedOpen wedOpen or {@code null} for none
   */
  public Hours setWedOpen(String wedOpen) {
    this.wedOpen = wedOpen;
    return this;
  }

  @Override
  public Hours set(String fieldName, Object value) {
    return (Hours) super.set(fieldName, value);
  }

  @Override
  public Hours clone() {
    return (Hours) super.clone();
  }

}
